---
- name: Ensure rbenv installed.
  homebrew: name=rbenv state=present
  register: rbenv_installed

- name: Ensure ruby-build installed.
  homebrew: name=ruby-build state=present

- name: Install ruby 2.4.1
  command: rbenv install 2.4.1
  ignore_errors: yes

- name: Install ruby 2.6.1
  command: rbenv install 2.6.1
  ignore_errors: yes

- name: rbenv Rehash
  command: rbenv rehash
