- name: Install Homebrew Cask packages
  tags:
    - cask
  command: brew cask install "{{ item }}"
  with_items:
    - 1password
    - caprine
    - chromedriver
    - discord
    - epubquicklook
    - evernote
    - google-backup-and-sync
    - google-chrome
    - hyper
    - jetbrains-toolbox
    - kap
    - qlcolorcode
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - sequel-pro
    - sketch
    - spotify
    - visual-studio-code
    - vlc
  ignore_errors: yes
